# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Apoorva Manjunath
description: "Apoorva Manjunath"
keywords: "apoorvam, apoorva, blog, developer, thoughtworks, golang"
url: https://apoorvam.github.io
baseurl:

google_analytics:
repo: http://github.com/apoorvam
disqus_shortname:
disqus_site_shortname:

# Author settings
author:
  name: Apoorva Manjunath
  job: "Software Developer"
  bio: "Passionate coder | Ex-ThoughtWorker | Music lover | DIY Enthusiast | Wanderlust"
  thumb: /images/apoorvam.jpg
  email: app.apoorva@gmail.com
  url: https://apoorvam.github.io
  github: https://github.com/apoorvam
  twitter: https://twitter.com/ItsApoorvaHere
  slideshare: https://www.slideshare.net/ApoorvaM4
  linkedin: https://www.linkedin.com/in/apoorvam6

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

include: [".well-known"]
exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
